/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//Package
package ProfessorOptionsWindows;
//Imports
import AdminMenuWindows.ProfessorWindow;
import static ProfessorOptionsWindows.ProfessorRegistryWindow.ProfessorList;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.table.DefaultTableModel;
/**
 **
 ** @author Luis Alonso Corella Chaves
 ** @date 2017-05-23 Martes
 **/
public class ProfessorDeleteWindow extends javax.swing.JFrame {
    /**
     * Creates new form ProfessorDeleteWindows
     */
    String names = "";
    public ProfessorDeleteWindow() {
        initComponents();
        setLocationRelativeTo(null);
        professorListTable.addMouseListener(new MouseAdapter() 
        {
            DefaultTableModel model = new DefaultTableModel();
            public void mouseClicked(MouseEvent e) 
            {
                int i = professorListTable.getSelectedRow();
                names = (professorListTable.getValueAt(i, 0).toString());
                String lastNames = (professorListTable.getValueAt(i, 1).toString());
                String ids = (professorListTable.getValueAt(i, 2).toString());
                String address = (professorListTable.getValueAt(i, 3).toString());
                String phones = (professorListTable.getValueAt(i, 4).toString());
                String emails = (professorListTable.getValueAt(i, 5).toString());
            }  
        });
        shows();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        professorListTable = new javax.swing.JTable();
        deleteProfessorButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        returnProfessor = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Lista de Profesores");

        professorListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Cédula", "Dirección", "Teléfono", "Email"
            }
        ));
        jScrollPane2.setViewportView(professorListTable);

        deleteProfessorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/eliminar-usuarios-icono-5461-48.png"))); // NOI18N
        deleteProfessorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProfessorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(deleteProfessorButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(deleteProfessorButton)
                .addGap(53, 53, 53))
        );

        returnProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/la-flecha-verde-de-la-izquierda-icono-7438-32.png"))); // NOI18N
        returnProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnProfessorMouseClicked(evt);
            }
        });
        jMenuBar1.add(returnProfessor);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void returnProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnProfessorMouseClicked
        ProfessorWindow professor = new ProfessorWindow();
        professor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returnProfessorMouseClicked
    private void deleteProfessorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProfessorButtonActionPerformed
        for (int i = 0; i < ProfessorList.size(); i++) 
        {
            if (names == ProfessorList.get(i).getName())
            {
                ProfessorList.remove(i);
            }
            shows();
        }
    }//GEN-LAST:event_deleteProfessorButtonActionPerformed
    public  void shows() {
        String tableList[][] = new String[ProfessorList.size()][6];
        for (int i = 0; i < ProfessorList.size(); i++) {
            tableList[i][0] = ProfessorList.get(i).getName();
            tableList[i][1] = ProfessorList.get(i).getLastName();
            tableList[i][2] = ProfessorList.get(i).getIdentificationCard();
            tableList[i][3] = ProfessorList.get(i).getAddress();
            tableList[i][4] = ProfessorList.get(i).getTelephoneNumber();
            tableList[i][5] = ProfessorList.get(i).getEmail();
        }
        professorListTable.setModel(new javax.swing.table.DefaultTableModel(
                tableList,
                new String[]{
                    "Nombre", "Apellido", "Cédula", "Dirección", "Teléfono", "Email"
                }
        ));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfessorDeleteWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfessorDeleteWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfessorDeleteWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfessorDeleteWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfessorDeleteWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteProfessorButton;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable professorListTable;
    private javax.swing.JMenu returnProfessor;
    // End of variables declaration//GEN-END:variables
}